name: Deploy to Web Server from Source

on:
  push:
    branches: [ "main" ]

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Connect to SSH
        env:
          HOSTNAME: ${{ secrets.SSH_HOST_NAME  }}
          USERNAME : ${{ secrets.SSH_USER_NAME  }}
          PASSWORD : ${{ secrets.SSH_PASSWORD  }}
         # You may pin to the exact commit or the version.
        # uses: webitsbr/github-to-ftp@b70bfbf3c11b8efa8bf4cb77308eab9cc5957a6c
        uses: webitsbr/github-to-ftp@1.0.1
        with:
          # ftp server
          server: ftp.dannywalsh.dev
          # ftp username
          username: CICD@dannywalsh.dev
          # ftp password
          password: 
          # Server port to connect to (read your web hosts docs)
          port: 21 # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: ./ # optional
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: ./ # optional
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: # optional
          # How verbose should the information be - minimal, standard, or verbose
          log-level: # optional
          # strict or loose
          security: # optional
        






      # If required, use the Cloud Run url output in later steps
